spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: ${DATABASE_INITIALIZATION_MODE}
    connectionProperties: useUnicode=true;characterEncoding=utf-8
  rabbitmq:
    host: ${RABBITMQ_HOST}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${SERVER_PORT}
